apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: repricer 
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: repricer 
    spec:
      initContainers:
        - name: chown
          image: busybox
          command:
          - chown
          - "65534:65534" # as specified in the Dockerfile
          - "/tmp/repricer"
          volumeMounts:
          - name: data
            mountPath: "/tmp/repricer"
      containers:
        - name: repricer 
          image: repricer.azurecr.io/repricer
          ports:
          - containerPort: 8080
          - containerPort: 9102
          livenessProbe:
            httpGet:
              path: /healthz/alive
              port: 9102
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 9102
          volumeMounts:
            - mountPath: "/tmp/repricer"
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: repricer-data-uid-jfc-please-please-please-work
