apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: repricer 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: repricer 
    spec:
      containers:
        - name: repricer 
          image: repricer.azurecr.io/repricer
          ports:
          - containerPort: 8080
          - containerPort: 9102
          livenessProbe:
            httpGet:
              path: /healthz/alive
              port: 9102
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 9102
