apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repricer-data-uid-jfc-please-please-please-work
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi
